os:
  - linux
  # We don't have an implementation that supports OSX (and poet_config_linux won't compile)
  # - osx

addons:
  apt:
    sources:
      - kubuntu-backports
    packages:
      - cmake

language: c

install:
  # heartbeats-simple dependency
  - wget https://github.com/libheartbeats/heartbeats-simple/archive/master.zip
  - unzip master.zip
  - rm master.zip
  - cd heartbeats-simple-master
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_INSTALL_PREFIX=_install ..
  - make
  - make install
  - cd ../..
  # energymon dependency (use default dummy implementation)
  - wget https://github.com/energymon/energymon/archive/master.zip
  - unzip master.zip
  - rm master.zip
  - cd energymon-master
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_INSTALL_PREFIX=_install ..
  - make
  - make install
  - cd ../..

script:
  - mkdir _build
  - cd _build
  - PKG_CONFIG_PATH="../heartbeats-simple-master/_build/_install/lib/pkgconfig:../energymon-master/_build/_install/lib/pkgconfig" cmake ..
  - make
